// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace F1StrategySite.MLModel
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [Required]
            [LoadColumn(0)]
            [ColumnName(@"driver_id")]
            public string Driver_id { get; set; }

            [Required]
            [LoadColumn(1)]
            [ColumnName(@"race_length")]
            public float Race_length { get; set; }

            [Required]
            [LoadColumn(2)]
            [ColumnName(@"year")]
            public float Year { get; set; }

            [Required]
            [LoadColumn(3)]
            [ColumnName(@"compound")]
            public string Compound { get; set; }

            [Required]
            [LoadColumn(4)]
            [ColumnName(@"stint_start_lap")]
            public float Stint_start_lap { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"tyre_life")]
            public float Tyre_life { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"driver_id")]
            public float[] Driver_id { get; set; }

            [ColumnName(@"race_length")]
            public float Race_length { get; set; }

            [ColumnName(@"year")]
            public float Year { get; set; }

            [ColumnName(@"compound")]
            public float[] Compound { get; set; }

            [ColumnName(@"stint_start_lap")]
            public float Stint_start_lap { get; set; }

            [ColumnName(@"tyre_life")]
            public float Tyre_life { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath(Path.Combine("MLModel", "MLModel1.mlnet"));

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        } 

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
